### ISSUE TITLE
Bug(OfflineWhitelistReforged):移除白名单功能失效

### ISSUE THREAD

**Issue by Five-willow** [Aimerny/MCDRPlugins#71]
#### 您使用的版本？ | Your usage version?
OfflineWhitelistReforged-v2.0.1.mcdr
#### 您使用的场景？ | Your usage scenarios?
搭配EasyAuth的高级自动登录功能
#### 您做了什么操作？ | What did you do?
在操作白名单添加移除
#### 您遇到了什么问题？ | What are your problems?
无法正常移除白名单，还是会显示在列表中，但玩家已经不能加入
移除后再次添加显示已经再白名单中，玩家已经无法加入
![控制台](https://github.com/user-attachments/assets/733ebd94-11f8-44ff-a04d-d9deb8616538)

![游戏内](https://github.com/user-attachments/assets/6e384b4b-47b5-405b-8aec-b915b6e508d4)

**Comment by Five-willow** [comment]
经过测试，只要是再服务器配置文件中将正版验证打开就会出现问题。与EasyAuth无关
MCDR插件：OfflineWhitelistReforged-v2.0.1.mcdr，WhitelistAPI-v1.2.0.mcdr
![插件](https://github.com/user-attachments/assets/4f4f1639-f689-44de-8075-c139a2f82d02)
只要开启正版验证，白名单插件的列表就无法被移除更新，且已经无法被重复添加白名单。
![测试](https://github.com/user-attachments/assets/f0998f6b-79ba-4119-abd9-a51f9734e3c8)
![控制台1](https://github.com/user-attachments/assets/63ef7750-cb99-4827-8fba-97ff5c91e9c2)

**Comment by Aimerny** [comment]
**原因**: `whitelist_api`会检查`server.properties`文件中的`online-mode`。在使用easyauth的时候是正版模式，此时remove会通过mc自己的`whitelist remove player`指令尝试操作，mc原版在清白名单貌似是以uuid为准的，和离线对不上所以会出现`Player is not whitelisted`的日志。

---
**解决**: 后续会更新下whitelist_api，支持强制使用离线模式清除白名单来兼容这种情况，请关注版本更新
