### ISSUE TITLE
[whitelistAPI] 🐛 Window 系统下白名单不会重载

### ISSUE THREAD

**Issue by XueK66** [Aimerny/MCDRPlugins#75]
#### 您使用的版本?
Win 10
WhitelistAPI 1.3.0

#### 您使用的场景？ | Your usage scenarios?
用于管理白名单

#### 您做了什么操作？ | What did you do?
修改白名单文件，然后读取白名单

#### 您遇到了什么问题？ | What are your problems?
白名单不会重载

#### 您期望的结果是怎样的？ | What is your expected outcome?
白名单能正常重载

#### (附加)必要的截图或日志 | (Additional) The capture or logs of this problem?
我打印了if语句、 `on_modified` 函数的 `event.src_path` 和 `self.__api.whitelist_file_path()`
![image](https://github.com/user-attachments/assets/73979dda-8dcd-4013-8a95-8611c2bc8ffe)

建议使用 pathlib 之类的库统一一下

谢谢佬的白名单管理（比自己写的好用多哩）

**Comment by Aimerny** [comment]
感谢支持~path问题后续会修复

**Comment by Aimerny** [comment]
resovled by #79
